### PR TITLE
Fix handling of IPv6 literal hosts in `Net::HTTPGenericRequest`

### LINKED ISSUE #73: Incorrect Host header for IPv6 addresses
When specifying a URI with an IPv6 address as the host, the Host header of the request contains the IPv6 address but it is not surrounded in brackets

e.g. With a locally running apache webserver, the following snippet results in an HTTP 400 Bad Request error because of the malformed host header (`Host: ::1` instead of `Host: [::1]`)
```
require 'net/http'
uri = URI.parse('http://[::1]')
Net::HTTP.get_response(uri)
```

### LINKED ISSUE #235: IPv6 host addr causes URI::InvalidComponentError since uri v1.1.0
We give the `URI.parse` result as `Net::HTTP.get` argument.
If we provide IPv6 address into `URI.parse`,
`Net::HTTP.get` causes `URI::InvalidComponentError` since uri v1.1.0.

### Reroduce code
```ruby
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'uri', '= 1.1.0'
  # gem 'uri', '= 1.0.4'
  gem 'webrick'
end

require 'net/http'

PORT = 24447

Thread.new do
  server = WEBrick::HTTPServer.new(Port: PORT)

  trap 'INT' do
    server.shutdown
  end

  puts "WEBrick server running on http://localhost:#{PORT}"
  server.start
end
sleep 0.2

puts "=== uri gem version ==="
puts URI::VERSION

puts "=== Use IPv4 localhost ==="
localhost = "localhost"

p URI.parse("http://#{localhost}:#{PORT}/api/plugins.flushBuffers")
p Net::HTTP.get(URI.parse("http://#{localhost}:#{PORT}/api/plugins.flushBuffers"))

puts "=== Use IPv6 localhost ==="
localhost = "[::1]"

p URI.parse("http://#{localhost}:#{PORT}/api/plugins.flushBuffers")
p Net::HTTP.get(URI.parse("http://#{localhost}:#{PORT}/api/plugins.flushBuffers"))
```

### Result with uri 1.1.0
It causes URI::InvalidComponentError with uri 1.1.0.
```
$ ruby -v uri.rb
ruby 3.4.7 (2025-10-08 revision 7a5688e2a2) +PRISM [x86_64-linux]
[2025-11-04 20:21:57] INFO  WEBrick 1.9.1
[2025-11-04 20:21:57] INFO  ruby 3.4.7 (2025-10-08) [x86_64-linux]
WEBrick server running on http://localhost:24447
[2025-11-04 20:21:57] INFO  WEBrick::HTTPServer#start: pid=660980 port=24447
=== uri gem version ===
1.1.0
=== Use IPv4 localhost ===
#<URI::HTTP http://localhost:24447/api/plugins.flushBuffers>
[2025-11-04 20:21:57] ERROR '/api/plugins.flushBuffers' not found.
::1 - - [04/Nov/2025:20:21:57 JST] "GET /api/plugins.flushBuffers HTTP/1.1" 404 295
- -> /api/plugins.flushBuffers
"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\">\n<HTML>\n  <HEAD><TITLE>Not Found</TITLE></HEAD>\n  <BODY>\n    <H1>Not Found</H1>\n    '/api/plugins.flushBuffers' not found.\n    <HR>\n    <ADDRESS>\n     WEBrick/1.9.1 (Ruby/3.4.7/2025-10-08) at\n     localhost:24447\n    </ADDRESS>\n  </BODY>\n</HTML>\n"
=== Use IPv6 localhost ===
#<URI::HTTP http://[::1]:24447/api/plugins.flushBuffers>
[2025-11-04 20:21:57] INFO  going to shutdown ...
[2025-11-04 20:21:57] INFO  WEBrick::HTTPServer#start done.
/home/watson/.rbenv/versions/3.4.7/lib/ruby/gems/3.4.0/gems/uri-1.1.0/lib/uri/http.rb:69:in 'URI::HTTP#check_host': bad component(expected host component):  (URI::InvalidComponentError)
        from /home/watson/.rbenv/versions/3.4.7/lib/ruby/gems/3.4.0/gems/uri-1.1.0/lib/uri/generic.rb:653:in 'URI::Generic#host='
        from /home/watson/.rbenv/versions/3.4.7/lib/ruby/3.4.0/net/http/generic_request.rb:230:in 'Net::HTTPGenericRequest#update_uri'
        from /home/watson/.rbenv/versions/3.4.7/lib/ruby/3.4.0/net/http.rb:2475:in 'Net::HTTP#begin_transport'
        from /home/watson/.rbenv/versions/3.4.7/lib/ruby/3.4.0/net/http.rb:2404:in 'Net::HTTP#transport_request'
        from /home/watson/.rbenv/versions/3.4.7/lib/ruby/3.4.0/net/http.rb:2378:in 'Net::HTTP#request'
        from /home/watson/.rbenv/versions/3.4.7/lib/ruby/3.4.0/net/http.rb:2249:in 'Net::HTTP#request_get'
        from /home/watson/.rbenv/versions/3.4.7/lib/ruby/3.4.0/net/http.rb:826:in 'block in Net::HTTP.get_response'
        from /home/watson/.rbenv/versions/3.4.7/lib/ruby/3.4.0/net/http.rb:1626:in 'Net::HTTP#start'
        from /home/watson/.rbenv/versions/3.4.7/lib/ruby/3.4.0/net/http.rb:1064:in 'Net::HTTP.start'
        from /home/watson/.rbenv/versions/3.4.7/lib/ruby/3.4.0/net/http.rb:824:in 'Net::HTTP.get_response'
        from /home/watson/.rbenv/versions/3.4.7/lib/ruby/3.4.0/net/http.rb:805:in 'Net::HTTP.get'
        from uri.rb:38:in '<main>'
```

### Expected (with uri 1.0.4)
No exception with uri 1.0.4
```
$ ruby -v uri.rb
ruby 3.4.7 (2025-10-08 revision 7a5688e2a2) +PRISM [x86_64-linux]
[2025-11-04 20:22:48] INFO  WEBrick 1.9.1
[2025-11-04 20:22:48] INFO  ruby 3.4.7 (2025-10-08) [x86_64-linux]
WEBrick server running on http://localhost:24447
[2025-11-04 20:22:48] INFO  WEBrick::HTTPServer#start: pid=661911 port=24447
=== uri gem version ===
1.0.4
=== Use IPv4 localhost ===
#<URI::HTTP http://localhost:24447/api/plugins.flushBuffers>
[2025-11-04 20:22:48] ERROR '/api/plugins.flushBuffers' not found.
::1 - - [04/Nov/2025:20:22:48 JST] "GET /api/plugins.flushBuffers HTTP/1.1" 404 295
- -> /api/plugins.flushBuffers
"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\">\n<HTML>\n  <HEAD><TITLE>Not Found</TITLE></HEAD>\n  <BODY>\n    <H1>Not Found</H1>\n    '/api/plugins.flushBuffers' not found.\n    <HR>\n    <ADDRESS>\n     WEBrick/1.9.1 (Ruby/3.4.7/2025-10-08) at\n     localhost:24447\n    </ADDRESS>\n  </BODY>\n</HTML>\n"
=== Use IPv6 localhost ===
#<URI::HTTP http://[::1]:24447/api/plugins.flushBuffers>
[2025-11-04 20:22:48] ERROR '/api/plugins.flushBuffers' not found.
::1 - - [04/Nov/2025:20:22:48 JST] "GET /api/plugins.flushBuffers HTTP/1.1" 404 283
"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\">\n<HTML>\n  <HEAD><TITLE>Not Found</TITLE></HEAD>\n  <BODY>\n    <H1>Not Found</H1>\n    '/api/plugins.flushBuffers' not found.\n    <HR>\n    <ADDRESS>\n     WEBrick/1.9.1 (Ruby/3.4.7/2025-10-08) at\n     :80\n    </ADDRESS>\n  </BODY>\n</HTML>\n"
- -> /api/plugins.flushBuffers
[2025-11-04 20:22:48] INFO  going to shutdown ...
[2025-11-04 20:22:48] INFO  WEBrick::HTTPServer#start done.
```

### PR DESCRIPTION
**Pull request by taketo1113**
### Background

When an IPv6 literal URI is passed as `uri_or_path` to `Net::HTTPGenericRequest`, an issue in IPv6 handling causes the HTTP request header `Host` to become incorrect.
For example, it becomes `::1:8000` instead of `[::1]:8000`.

This incorrect `Host` header leads to the following problems:
- Fix #235
  - Requests to `http://[::1]` result in an error with uri v1.0.4 - 1.1.0
- Fix #73
  - An HTTP 400 Bad Request error occurs due to the malformed `Host` header

### Details

This Pull Request fixes the handling of IPv6 literal hosts in `Net::HTTPGenericRequest` when a URI with an IPv6 literal is passed.
(This Pull Request revises and improves upon Pull Request #156.)

With this change, the `Host` header in HTTP requests generated from IPv6 literal URIs will now have the correct format.
Since this fix only resolves cases that previously caused HTTP 400 Bad Request errors, I think it does not introduce any compatibility issues.

- Before: `Host: 2001:db8::1:8000`
- After: `Host: [2001:db8::1]:8000`

The behavior for non-IPv6 literal URIs remains unchanged.

### Expected behavior
- The `Host` header (`req['Host']`) returns an correct value
- No error occurs in `Net::HTTPGenericRequest#update_uri` with `http://[::1]`

```ruby
require 'net/http'

# http://[2001:db8::1]:8000
req = Net::HTTP::Get.new(URI.parse("http://[2001:db8::1]:8000"))
req['Host']
#=> "[2001:db8::1]:8000"

req.update_uri("test", 8001, false)
req.uri.host
#=> "[2001:db8::1]"

# http://[::1]:8000
req = Net::HTTP::Get.new(URI.parse("http://[::1]:8000"))
req['Host']
#=> "[::1]:8000"

req.update_uri("example.com", 8001, false)
req.uri.host
#=> "[::1]"
```

### Actual behavior
- The `Host` header (`req['Host']`) returns an incorrect value
- `Net::HTTPGenericRequest#update_uri` raises `URI::InvalidComponentError` with `http://[::1]` when using uri v1.0.4 - 1.1.0

```ruby
require 'net/http'

# http://[2001:db8::1]:8000
req = Net::HTTP::Get.new(URI.parse("http://[2001:db8::1]:8000"))
req['Host']
#=> "2001:db8::1:8000"

req.update_uri("example.com", 8001, false)
req.uri.host
#=> "2001"

# http://[::1]:8000
req = Net::HTTP::Get.new(URI.parse("http://[::1]:8000"))
req['Host']
#=> "::1:8000"

req.update_uri("example.com", 8001, false)
/Users/taketo/path/ruby/3.4.0/gems/uri-1.1.0/lib/uri/http.rb:69:in 'URI::HTTP#check_host': bad component(expected host component):  (URI::InvalidComponentError)
	from /Users/taketo/path/ruby/3.4.0/gems/uri-1.1.0/lib/uri/generic.rb:653:in 'URI::Generic#host='
	from /Users/taketo/path/ruby/3.4.0/gems/net-http-0.7.0/lib/net/http/generic_request.rb:255:in 'Net::HTTPGenericRequest#update_uri'
...
```

### System configuration
- ruby: 3.4.7
- net-http: 0.7.0
- uri: 1.1.0

### Additional Information
~~The CI errors in `test (2.7 / windows-latest)` and `test (2.6 / windows-latest)` are unrelated to this fix and will be resolved once #236 is merged.~~
(It resolved by power_assert v3.0.1.)

### CODE REVIEW

File: lib/net/http/generic_request.rb [hunk 1]
```diff
@@ -245,7 +248,7 @@ def update_uri(addr, port, ssl) # :nodoc: internal use only
     end
 
     if host = self['host']
-      host.sub!(/:.*/m, '')
+      host = URI.parse("#{scheme}://#{host}").host
```
Comment (sorah) [inline lib/net/http/generic_request.rb]:
```suggestion
      host = URI.parse("//#{host}").host # Remove a port component from the existing Host header
```

**Comment by HoneyryderChuck** [comment]
At this point you could just use https://docs.ruby-lang.org/en/master/URI/HTTP.html#method-i-authority ?

**Comment by sorah** [comment]
> The `URI::HTTP#authority` method was added in Ruby 3.0, but since the net-http gem supports Ruby 2.6 and later, I don't think we can use it.

I agree raising minimum version to 3.0 as the present minimum version is too outdated. It's also worth to specify version to `> 0.10.0`.

**Comment by taketo1113** [comment]
> I agree raising minimum version to 3.0 as the present minimum version is too outdated. It's also worth to specify version to > 0.10.0.

Should this Pull Request handle raising the minimum Ruby version?

Personally, since this Pull Request is a bug fix, I think it's better not to include breaking changes such as raising the minimum Ruby version.
Also, since the system Ruby on macOS 26 (released in September 2025) is still 2.6.10, I'd appreciate it if older Ruby versions could continue to be supported. (That said, Ruby 4.0 is coming soon, though…)

---
As for the CI errors, I believe they will pass if you rerun the workflow.
I tried running it several times in my forked repository, and all tests passed successfully.
- https://github.com/taketo1113/net-http/actions/runs/19216332542/job/54973767896

**Comment by sorah** [comment]
> Should this Pull Request handle raising the minimum Ruby version?

Yes, that's definitely fine along with a fix requires newer Ruby version. However if URI 0.10.0 still supports Ruby 2.6, then specifying `uri >= 0.10.0` as a dependency works sufficiently instead of raising minimum version.

**Comment by taketo1113** [comment]
I misread it. I will change it to `>=`.
